version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 3000:3000
  api:
    build: 
      context: ./
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 9000:9000